import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DataTable } from "@/components/common/DataTable";
import { Input } from "@/components/ui/input";
import { QueryState } from "@/components/QueryState";
import { SidePanel, SidePanelContent, SidePanelDescription, SidePanelFooter, SidePanelHeader, SidePanelTitle } from "@/components/ui/side-panel";
import { getApiErrorMessage } from "@/lib/api";
import { useCreateDashboardCustomer, useDashboardCustomer, useDashboardCustomers } from "@/hooks/useSiteDashboard";
import { toast } from "sonner";

function Money({ value }: { value: number }) { return <span>KES {value.toLocaleString()}</span>; }

export function CustomersPage() {
  const query = useDashboardCustomers(); const [open, setOpen] = useState(false); const create = useCreateDashboardCustomer();
  return <QueryState isLoading={query.isLoading} isError={query.isError} error={query.error} data={query.data}>{customers => <div className="space-y-6"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-semibold">Customers</h1><p className="text-muted-foreground">Customer ownership and billing overview.</p></div><Button onClick={() => setOpen(true)}>New customer</Button></div><DataTable data={customers} getRowKey={customer => customer.id} searchPlaceholder="Search customers…" columns={[{ key: "name", header: "Customer", searchable: true, searchValue: customer => `${customer.name} ${customer.contactEmail ?? ""}`, render: customer => <Link className="font-medium text-primary hover:underline" to={`/app/customers/${customer.id}`}>{customer.name}</Link> }, { key: "contact", header: "Contact", render: customer => <span className="text-sm">{customer.contactEmail ?? "No email"}<br /><span className="text-muted-foreground">{customer.contactPhone ?? "No phone"}</span></span> }, { key: "projects", header: "Projects", render: customer => customer.siteCount }, { key: "paid", header: "Paid", render: customer => <Money value={customer.totalPaid} /> }, { key: "balance", header: "Balance", render: customer => <Money value={customer.balance} /> }, { key: "health", header: "Health", render: customer => <div className="flex flex-wrap gap-1">{Object.entries(customer.health).map(([status, count]) => <Badge key={status} variant="outline">{status.replace(/_/g, " ")}: {count}</Badge>)}</div> }]} /><SidePanel open={open} onOpenChange={setOpen}><SidePanelContent><SidePanelHeader><SidePanelTitle>New customer</SidePanelTitle><SidePanelDescription>Add a customer for project ownership.</SidePanelDescription></SidePanelHeader><form className="grid gap-4 px-6 py-5" onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await create.mutateAsync({ name: String(form.get("name")), contactEmail: String(form.get("email") || "") || undefined, contactPhone: String(form.get("phone") || "") || undefined }); toast.success("Customer created"); setOpen(false); } catch (error) { toast.error(getApiErrorMessage(error)); } }}><Input name="name" placeholder="Customer name" required /><Input name="email" type="email" placeholder="Contact email" /><Input name="phone" placeholder="Contact phone" /><SidePanelFooter><Button type="submit" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create customer"}</Button></SidePanelFooter></form></SidePanelContent></SidePanel></div>}</QueryState>;
}

export function CustomerDetailPage() {
  const id = useParams().id ?? ""; const query = useDashboardCustomer(id);
  return <QueryState isLoading={query.isLoading} isError={query.isError} error={query.error} data={query.data}>{customer => <div className="space-y-6"><Link to="/app/customers" className="text-sm text-primary hover:underline">← All customers</Link><div><h1 className="text-2xl font-semibold">{customer.name}</h1><p className="text-muted-foreground">{customer.contactEmail ?? "No email"} · {customer.contactPhone ?? "No phone"}</p></div><div className="grid gap-4 sm:grid-cols-3">{[["Total billed", customer.totalBilled], ["Historically paid", customer.totalPaid], ["Outstanding balance", customer.balance]].map(([label, value]) => <Card key={label as string}><CardHeader><CardTitle className="text-sm">{label as string}</CardTitle></CardHeader><CardContent className="text-xl font-semibold"><Money value={value as number} /></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Projects owned</CardTitle></CardHeader><CardContent><DataTable data={customer.projects ?? []} getRowKey={project => project.id} searchPlaceholder="Search projects…" columns={[{ key: "project", header: "Project", searchable: true, searchValue: project => `${project.name} ${project.slug}`, render: project => <Link className="font-medium text-primary hover:underline" to={`/app/projects/${project.slug}`}>{project.name}</Link> }, { key: "domain", header: "Domain", render: project => project.domain }, { key: "status", header: "Status", render: project => <Badge variant="outline">{project.status}</Badge> }, { key: "paid", header: "Paid", render: project => <Money value={project.totalPaid} /> }, { key: "balance", header: "Balance", render: project => <Money value={project.balance} /> }]} emptyMessage="No projects are linked to this customer." /></CardContent></Card></div>}</QueryState>;
}
