import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, getApiErrorMessage } from "@/lib/api";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DataTable } from "@/components/common/DataTable";

type AdminUser = { id: string; email: string; role: string; twoFactorEnabled: boolean; createdAt: string; active?: boolean };

export function AdminUsersPage() {
  const client = useQueryClient();
  const [params, setParams] = useSearchParams();
  const pageSize = 15;
  const page = Math.max(0, Number(params.get("page") ?? 0) || 0);
  const search = params.get("q") ?? "";
  const updateTable = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.delete("page"); setParams(next); };
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState("admin"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AdminUser | null>(null); const [editEmail, setEditEmail] = useState(""); const [editRole, setEditRole] = useState("admin");
  const users = useQuery({ queryKey: ["admin-users", page, search], queryFn: async () => (await api.get<{ users: AdminUser[]; total: number; limit: number; offset: number; hasMore: boolean }>("/admin/users", { params: { limit: pageSize, offset: page * pageSize, q: search || undefined } })).data });
  const refresh = () => void client.invalidateQueries({ queryKey: ["admin-users"] });
  const create = useMutation({ mutationFn: async () => (await api.post<AdminUser>("/admin/users", { email, password, role })).data, onSuccess: () => { setEmail(""); setPassword(""); setRole("admin"); setOpen(false); refresh(); toast.success("Admin user created"); }, onError: error => toast.error(getApiErrorMessage(error)) });
  const update = useMutation({ mutationFn: async ({ id, changes }: { id: string; changes: Record<string, unknown> }) => api.patch(`/admin/users/${id}`, changes), onSuccess: () => { refresh(); toast.success("User updated"); }, onError: error => toast.error(getApiErrorMessage(error)) });
  const remove = useMutation({ mutationFn: async (id: string) => api.delete(`/admin/users/${id}`), onSuccess: () => { refresh(); toast.success("User deleted"); }, onError: error => toast.error(getApiErrorMessage(error)) });
  const edit = (user: AdminUser) => { setEditing(user); setEditEmail(user.email); setEditRole(user.role); };
  const sharedUsers = users.data?.users ?? [];
  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">Admin users</h1><p className="text-muted-foreground">Manage administrator and service accounts.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button>Create user</Button></DialogTrigger><DialogContent className="left-auto right-0 top-0 h-full max-w-md translate-x-0 translate-y-0 rounded-none sm:rounded-l-lg"><DialogHeader><DialogTitle>Create admin user</DialogTitle><DialogDescription>Create a service account for Scribed or another administrator.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={event => { event.preventDefault(); create.mutate(); }}><div><Label>Email</Label><Input required type="email" value={email} onChange={event => setEmail(event.target.value)} /></div><div><Label>Password</Label><Input required minLength={8} type="password" value={password} onChange={event => setPassword(event.target.value)} /></div><div><Label>Role</Label><select className="flex h-9 w-full rounded-md border bg-background px-3 text-sm" value={role} onChange={event => setRole(event.target.value)}><option value="admin">Admin</option><option value="operator">Operator</option><option value="viewer">Viewer</option></select></div><p className="text-xs text-muted-foreground">Two-factor authentication is disabled initially.</p><DialogFooter><Button type="submit" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create user"}</Button></DialogFooter></form></DialogContent></Dialog></div>
    <DataTable data={sharedUsers} mode="server" total={users.data?.total ?? 0} page={page} pageSize={pageSize} search={{ value: search, onChange: value => updateTable("q", value) }} onPageChange={next => updateTable("page", String(next))} isLoading={users.isLoading} getRowKey={user => user.id} columns={[{ key: "email", header: "Email", searchable: true, searchValue: user => `${user.email} ${user.role}`, render: user => <div><p>{user.email}</p><p className="text-xs text-muted-foreground">{user.role} · {user.twoFactorEnabled ? "2FA enabled" : "2FA disabled"} · {user.active === false ? "Suspended" : "Active"}</p></div> }, { key: "actions", header: "Actions", render: user => <div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => edit(user)}>Edit</Button><Button size="sm" variant="outline" onClick={() => update.mutate({ id: user.id, changes: { active: user.active === false } })}>{user.active === false ? "Reactivate" : "Suspend"}</Button><Button size="sm" variant="destructive" onClick={() => { if (window.confirm(`Delete ${user.email}?`)) remove.mutate(user.id); }}>Delete</Button></div> }]} />
    <Dialog open={editing !== null} onOpenChange={value => { if (!value) setEditing(null); }}><DialogContent className="left-auto right-0 top-0 h-full max-w-md translate-x-0 translate-y-0 rounded-none sm:rounded-l-lg"><DialogHeader><DialogTitle>Edit user</DialogTitle><DialogDescription>Update the account email or role.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={event => { event.preventDefault(); if (editing) { update.mutate({ id: editing.id, changes: { email: editEmail, role: editRole } }); setEditing(null); } }}><div><Label>Email</Label><Input required type="email" value={editEmail} onChange={event => setEditEmail(event.target.value)} /></div><div><Label>Role</Label><select className="flex h-9 w-full rounded-md border bg-background px-3 text-sm" value={editRole} onChange={event => setEditRole(event.target.value)}><option value="admin">Admin</option><option value="operator">Operator</option><option value="viewer">Viewer</option></select></div><DialogFooter><Button type="submit" disabled={update.isPending}>Save changes</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}
