import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Github, ExternalLink, RefreshCw } from "lucide-react";
import QRCode from "qrcode";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuthStore } from "@/store/authStore";
import { useGitHubInstallUrl, useGitHubStatus, useUnlinkGitHub } from "@/hooks/useDeployments";
import { toast } from "sonner";
import { api, getApiErrorMessage } from "@/lib/api";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

type Setup = { secret: string; otpauthUri: string; recoveryCodes: string[] };
type Tab = "general" | "security" | "integrations";

export function ProfileSettingsPage() {
  const email = useAuthStore(s => s.email); const role = useAuthStore(s => s.role);
  const [tab, setTab] = useState<Tab>("general"); const [unlinkOpen, setUnlinkOpen] = useState(false);
  const [displayName, setDisplayName] = useState(""); const [setup, setSetup] = useState<Setup | null>(null); const [qrCode, setQrCode] = useState<string | null>(null); const [setupCode, setSetupCode] = useState("");
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [disablePassword, setDisablePassword] = useState(""); const [disableCode, setDisableCode] = useState("");
  const account = useQuery({ queryKey: ["auth", "me"], queryFn: async () => (await api.get<{ displayName?: string; avatarUrl?: string; totpEnabled?: boolean }>("/auth/me")).data });
  const github = useGitHubStatus(); const install = useGitHubInstallUrl(); const unlink = useUnlinkGitHub();
  const profile = useMutation({ mutationFn: () => api.patch("/auth/me", { displayName }) }); const password = useMutation({ mutationFn: () => api.post("/auth/password", { currentPassword, newPassword }) });
  const setup2fa = useMutation({ mutationFn: async () => (await api.post<Setup>("/auth/2fa/setup")).data }); const enable2fa = useMutation({ mutationFn: () => api.post("/auth/2fa/enable", { code: setupCode }) }); const disable2fa = useMutation({ mutationFn: () => api.post("/auth/2fa/disable", { currentPassword: disablePassword, code: disableCode }) });
  useEffect(() => { if (account.data?.displayName !== undefined) setDisplayName(account.data.displayName); }, [account.data?.displayName]);
  useEffect(() => { if (setup) void QRCode.toDataURL(setup.otpauthUri, { width: 220, margin: 1 }).then(setQrCode); else setQrCode(null); }, [setup]);
  const run = async (action: () => Promise<unknown>, message: string, reset?: () => void) => { try { await action(); reset?.(); await account.refetch(); toast.success(message); } catch (error) { toast.error(getApiErrorMessage(error)); } };
  return <div className="max-w-5xl space-y-6"><div><h2 className="text-lg font-semibold">Settings</h2><p className="text-sm text-muted-foreground">Manage your account, security, and connected services.</p></div><div className="flex gap-1 border-b"><Button variant={tab === "general" ? "secondary" : "ghost"} onClick={() => setTab("general")}>General</Button><Button variant={tab === "security" ? "secondary" : "ghost"} onClick={() => setTab("security")}>Security</Button><Button variant={tab === "integrations" ? "secondary" : "ghost"} onClick={() => setTab("integrations")}>Integrations</Button></div>
    {tab === "general" && <Card><CardHeader><CardTitle>Profile</CardTitle><CardDescription>Update the identity shown in the dashboard.</CardDescription></CardHeader><CardContent className="max-w-2xl space-y-5"><div className="flex items-center gap-3">{account.data?.avatarUrl && <img src={account.data.avatarUrl} alt="Profile" className="h-12 w-12 rounded-full object-cover" onError={e => { e.currentTarget.style.display = "none"; }} />}<span className="text-xs text-muted-foreground">Profile image is loaded from Gravatar when available.</span></div><div className="grid max-w-xl gap-4 sm:grid-cols-2"><div className="space-y-1"><Label>Email</Label><Input readOnly value={email ?? ""} /></div><div className="space-y-1"><Label>Role</Label><Input readOnly value={role ?? ""} /></div><div className="space-y-1"><Label>Display name</Label><Input value={displayName} onChange={e => setDisplayName(e.target.value)} maxLength={80} /></div></div><Button disabled={profile.isPending} onClick={() => run(() => profile.mutateAsync(), "Profile updated")}>{profile.isPending ? "Saving…" : "Save profile"}</Button></CardContent></Card>}
    {tab === "security" && <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Password</CardTitle><CardDescription>Use at least 8 characters and keep it unique.</CardDescription></CardHeader><CardContent className="max-w-xl space-y-4"><div className="space-y-1"><Label>Current password</Label><Input type="password" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} /></div><div className="space-y-1"><Label>New password</Label><Input type="password" minLength={8} value={newPassword} onChange={e => setNewPassword(e.target.value)} /></div><Button disabled={password.isPending || !currentPassword || newPassword.length < 8} onClick={() => run(() => password.mutateAsync(), "Password changed", () => { setCurrentPassword(""); setNewPassword(""); })}>{password.isPending ? "Changing…" : "Change password"}</Button></CardContent></Card>
      <Card><CardHeader><CardTitle>Two-factor authentication</CardTitle><CardDescription>{account.data?.totpEnabled ? "Your account is protected by an authenticator app." : "Add an authenticator app as a second layer of protection."}</CardDescription></CardHeader><CardContent className="space-y-5">{account.data?.totpEnabled ? <><div className="rounded-md border border-emerald-500/30 bg-emerald-500/5 p-3 text-sm text-emerald-600">Two-factor authentication is enabled.</div><div className="space-y-3 border-t pt-4"><p className="text-sm font-medium">Disable two-factor authentication</p><div className="grid gap-3 sm:grid-cols-2"><Input type="password" placeholder="Current password" value={disablePassword} onChange={e => setDisablePassword(e.target.value)} /><Input placeholder="Authenticator or recovery code" value={disableCode} onChange={e => setDisableCode(e.target.value)} /></div><Button variant="outline" disabled={disable2fa.isPending || !disablePassword || !disableCode} onClick={() => run(() => disable2fa.mutateAsync(), "Two-factor authentication disabled", () => { setDisablePassword(""); setDisableCode(""); })}>Disable 2FA</Button></div></> : !setup ? <Button onClick={async () => { try { setSetup(await setup2fa.mutateAsync()); } catch (error) { toast.error(getApiErrorMessage(error)); } }} disabled={setup2fa.isPending}>{setup2fa.isPending ? "Preparing…" : "Enable 2FA"}</Button> : <div className="space-y-4"><p className="text-sm text-muted-foreground">Scan the QR code with Google Authenticator, save the recovery codes, then verify the app code.</p>{qrCode && <img src={qrCode} alt="Authenticator setup QR code" className="h-44 w-44 rounded border bg-white p-2" />}<div className="space-y-1"><Label>Manual setup key</Label><Input readOnly value={setup.secret} className="max-w-md font-mono text-xs" /></div><div className="max-w-md rounded-md border p-3"><p className="text-sm font-medium">Recovery codes</p><p className="mb-2 text-xs text-muted-foreground">Store these safely. Each code can be used once.</p><div className="grid grid-cols-2 gap-1 font-mono text-xs">{setup.recoveryCodes.map(code => <span key={code}>{code}</span>)}</div></div><div className="flex max-w-md gap-2"><Input inputMode="numeric" placeholder="6-digit code" value={setupCode} onChange={e => setSetupCode(e.target.value)} maxLength={6} /><Button disabled={enable2fa.isPending || setupCode.length !== 6} onClick={() => run(() => enable2fa.mutateAsync(), "Two-factor authentication enabled", () => { setSetup(null); setSetupCode(""); })}>Verify and enable</Button></div></div>}</CardContent></Card></div>}
    {tab === "integrations" && <Card><CardHeader><CardTitle className="flex items-center gap-2"><Github className="h-5 w-5" /> GitHub access</CardTitle><CardDescription>Connect GitHub for private repository deployments and webhooks.</CardDescription></CardHeader><CardContent className="space-y-4">{github.isLoading ? <p className="text-sm text-muted-foreground">Checking GitHub connection…</p> : github.data?.connected ? <div className="flex max-w-xl flex-wrap items-center justify-between gap-3 rounded-md border p-4"><div><p className="font-medium">Connected</p><p className="text-sm text-muted-foreground">{github.data.accountLogin ?? "Installation configured"}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => github.refetch()}><RefreshCw className="h-4 w-4" />Refresh</Button><Button variant="destructive" size="sm" onClick={() => setUnlinkOpen(true)}>Unlink</Button></div></div> : <Button onClick={async () => { try { window.location.assign((await install.mutateAsync()).url); } catch (error) { toast.error(getApiErrorMessage(error)); } }} disabled={install.isPending}><ExternalLink className="h-4 w-4" />Connect GitHub</Button>}</CardContent></Card>}
    <AlertDialog open={unlinkOpen} onOpenChange={setUnlinkOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Unlink GitHub?</AlertDialogTitle><AlertDialogDescription>This removes Gatekeeperd’s stored GitHub installation association.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={async () => { try { await unlink.mutateAsync(); toast.success("GitHub installation unlinked"); } catch (error) { toast.error(getApiErrorMessage(error)); } finally { setUnlinkOpen(false); } }}>Unlink GitHub</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
