import { RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { QueryState } from "@/components/QueryState";
import { useNotificationAction, useNotifications } from "@/hooks/useProjects";
import { Input } from "@/components/ui/input";
import { useMemo, useState } from "react";

export function NotificationsPage() {
  const notifications = useNotifications(100);
  const action = useNotificationAction(); const [severity, setSeverity] = useState("all"); const [search, setSearch] = useState("");
  const filtered = useMemo(() => (notifications.data ?? []).filter(item => (severity === "all" || item.severity === severity) && `${item.title} ${item.message} ${item.action}`.toLowerCase().includes(search.toLowerCase())), [notifications.data, search, severity]);
  return <div className="space-y-6"><div><p className="text-muted-foreground">Recent system, deployment, payment, and integration events.</p></div><Card><CardHeader className="space-y-3"><div className="flex flex-row items-center justify-between"><CardTitle className="text-sm">Notifications</CardTitle><Button variant="ghost" size="icon" onClick={() => notifications.refetch()} aria-label="Refresh notifications"><RefreshCw className="h-4 w-4" /></Button></div><div className="flex flex-wrap gap-2"><Input className="max-w-sm" placeholder="Search notifications" value={search} onChange={e => setSearch(e.target.value)} /><select className="h-9 rounded-md border bg-background px-3 text-sm" value={severity} onChange={e => setSeverity(e.target.value)}><option value="all">All severities</option><option value="error">Errors</option><option value="warning">Warnings</option><option value="info">Info</option></select></div></CardHeader><CardContent><QueryState isLoading={notifications.isLoading} isError={notifications.isError} error={notifications.error} data={filtered}>{items => items.length ? <div className="space-y-2">{items.map(item => <div key={item.id} className="flex items-start justify-between gap-4 rounded-md border p-3"><div><p className="text-sm font-medium capitalize">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.message}</p><p className="mt-2 text-[11px] text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</p><div className="mt-2 flex gap-2"><Button size="sm" variant="ghost" disabled={action.isPending || item.read} onClick={() => action.mutate({ id: item.id, state: "read" })}>{item.read ? "Read" : "Mark read"}</Button><Button size="sm" variant="ghost" disabled={action.isPending} onClick={() => action.mutate({ id: item.id, state: "dismissed" })}>Dismiss</Button><Button size="sm" variant="ghost" disabled={action.isPending} onClick={() => action.mutate({ id: item.id, state: "archived" })}>Archive</Button></div></div><Badge variant={item.severity === "error" ? "destructive" : item.severity === "warning" ? "secondary" : "outline"}>{item.severity}</Badge></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">No notifications match the current filters.</p>}</QueryState></CardContent></Card></div>;
}
