import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { QueryState } from "@/components/QueryState";
import { toast } from "sonner";
import { getApiErrorMessage } from "@/lib/api";
import { useCreateDockerResource, useDeleteDockerResource, useNetworks, useVolumes } from "@/hooks/useDockerResources";

export function DockerResourcesPage({ kind }: { kind: "networks" | "volumes" }) {
  const query = kind === "networks" ? useNetworks() : useVolumes();
  const create = useCreateDockerResource(kind); const remove = useDeleteDockerResource(kind); const [name, setName] = useState(""); const [deleteTarget, setDeleteTarget] = useState<string | null>(null);
  const createResource = async (e: React.FormEvent) => { e.preventDefault(); try { await create.mutateAsync({ name, driver: "bridge" }); setName(""); toast.success(`${kind === "networks" ? "Network" : "Volume"} created`); } catch (error) { toast.error(getApiErrorMessage(error)); } };
  return <div className="space-y-6"><div><p className="text-muted-foreground">Manage Docker {kind} used by containers and deployments.</p></div><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Create {kind === "networks" ? "network" : "volume"}</CardTitle></CardHeader><CardContent className="pt-2"><form onSubmit={createResource} className="flex max-w-xl items-end gap-2"><div className="flex-1 space-y-1"><Label>Name</Label><Input required value={name} onChange={e => setName(e.target.value)} placeholder={kind === "networks" ? "app-network" : "app-data"} /></div><Button type="submit"><Plus className="h-4 w-4" />Create</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Available {kind}</CardTitle></CardHeader><CardContent><QueryState isLoading={query.isLoading} isError={query.isError} error={query.error} data={query.data}>{items => <div className="space-y-2">{items.map(item => <div key={item.name} className="flex items-center justify-between rounded-md border p-3"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.driver} · {"scope" in item ? item.scope : ""}{["bridge", "host", "none"].includes(item.name) && " · Docker built-in"}</p>{kind === "networks" && <><p className="mt-2 text-xs text-muted-foreground">Containers: {("containers" in item && item.containers.length > 0) ? item.containers.join(", ") : "None attached"}</p><p className="mt-1 text-xs text-muted-foreground">{("gateway" in item && item.gateway) ? `Gateway: ${item.gateway}` : "Gateway unavailable"}{("subnet" in item && item.subnet) ? ` · Subnet: ${item.subnet}` : ""}</p></>}</div>{!["bridge", "host", "none"].includes(item.name) && <Button size="icon" variant="ghost" className="text-destructive" title={`Delete ${item.name}`} onClick={() => setDeleteTarget(item.name)}><Trash2 className="h-4 w-4" /></Button>}</div>)}{items.length === 0 && <p className="py-6 text-center text-sm text-muted-foreground">No {kind} found. Create one before selecting it in a deployment.</p>}</div>}</QueryState></CardContent></Card><AlertDialog open={deleteTarget !== null} onOpenChange={(open) => !open && setDeleteTarget(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {deleteTarget}?</AlertDialogTitle><AlertDialogDescription>This permanently removes the Docker {kind === "networks" ? "network" : "volume"}. Containers using it may stop working.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" disabled={remove.isPending} onClick={async () => { if (!deleteTarget) return; try { await remove.mutateAsync(deleteTarget); toast.success("Resource deleted"); setDeleteTarget(null); } catch (error) { toast.error(getApiErrorMessage(error)); } }}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
